#!/bin/bash

if [[ "$#" -ne 3 ]];
then
    echo "Invalid number of params!"
    echo "Usage: test <log_dir> <dataset_dir> <iterations>"
    exit
fi

MY_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

LOG_FILE_PREFIX="comp_perf"
LOG_DIR=$1
DATASET_DIR=$2
ITERATIONS=$3

_run_iteration()
{
    ITERATION=$1
    LOG_FILE=$LOG_DIR/$LOG_FILE_PREFIX.$ITERATION
    
    $MY_DIR/src/experiment $DATASET_DIR -bg4foasi > $LOG_FILE
}


echo "Compression: Begin"
COUNTER=1
while [[ $COUNTER -le $ITERATIONS ]];
do
    echo "Compression: Iteration: $COUNTER"
    _run_iteration $COUNTER
    ((COUNTER++))
done

echo "Compression: Done"
